"""creation table emprunts

Revision ID: cdc43f0bc810
Revises: 
Create Date: 2026-05-14 02:50:25.994832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc43f0bc810'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprunts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.Column('date_emprunt', sa.DateTime(), nullable=True),
    sa.Column('date_retour_prevue', sa.DateTime(), nullable=False),
    sa.Column('date_retour_effectif', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprunts')
    # ### end Alembic commands ###
